services:
  - type: web
    name: "turboimpot-backend"
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: "My Disk"
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~16.14.2
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: "turboimpot"
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: "turboimpot"
    plan: starter
